# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd9ebf77114d5f215000ba9e02d038136e810298b68db2a413f998b8fa02695147141514c736eacab41b5e77ea6d7f79da24c335cde6fbabf5c82b73d1e2a9ce

test:
  secret_key_base: 5b6225e0e4f35a89af673cbb3af296708ee3b2646e60d1ca0c70894dd31cc4edf5178f695ac6f6c2cd2cba7f4dbe34bfbb4e210febea807a4be8ec48de1a808c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
